# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StyleExporter
                                 A QGIS plugin
 Plugin export styles of selected layers to individual file with name same as layers name.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-01
        copyright            : (C) 2024 by Łukasz Świątek
        email                : lukasz.swiatek1996@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StyleExporter class from file StyleExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .style_exporter import StyleExporter
    return StyleExporter(iface)
